spring:
  application:
    name: authentication-service
server:
  address: '0.0.0.0'
  port: 10061
env:
  url:
    person-service: http://${person_service_ip}:10011/personService
    user-service: http://${user_service_ip}:10021/userService
    role-service: http://${role_service_ip}:10031/roleService
    session-service: http://${session_service_ip}:10081/sessionService