spring:
  application:
    name: authentication-service
server:
  address: '0.0.0.0'
  port: 10061
env:
  url:
    person-service: ${PERSON_SERVICE}
    user-service: ${USER_SERVICE}
    role-service: ${ROLE_SERVICE}
    session-service: ${SESSION_SERVICE}
