spring:
  application:
    name: authentication-service
server:
  address: '0.0.0.0'
  port: 10061
env:
  url:
    person-service: ${PERSON_SERVICE}/personService
    user-service: ${USER_SERVICE}/userService
    role-service: ${ROLE_SERVICE}/roleService
    session-service: ${SESSION_SERVICE}/sessionService